name: ci

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'LICENSE'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'LICENSE'
    - '**.md'

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable, nightly]
        exclude:
        - toolchain: nightly
          os: windows-latest
        - toolchain: nightly
          os: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - if: matrix.toolchain == 'nightly'
      name: Test no-std compatibility
      working-directory: ./tests/no_std
      run: cargo build
