name: Fastdiv Test

on:
  push:
  pull_request:
    paths-ignore:
    - 'LICENSE'
    - '**.md'

env:
  RUST_BACKTRACE: 1

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
